version: '3'
services:
  rabbit:
    image: rabbitmq:alpine
    container_name: rabbit
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for RabbitMQ GUI
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: always
    depends_on:
      - zookeeper

  producer:
    image: btc-app
    container_name: btc-app
    build: ./producer
    environment:
      BROKER: kafka
      AMQP_SERVER_URL: amqp://guest:guest@rabbit:5672/
      KAFKA_SERVER_URL: kafka:9092
      KAFKA_LOG_TOPIC: logs
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rabbit
      - kafka

  consumer:
    image: logger
    container_name: logger
    build: ./consumer
    environment:
      BROKER: kafka
      CONSUME_LOG_LEVEL: ERROR
      AMQP_SERVER_URL: amqp://guest:guest@rabbit:5672/
      KAFKA_SERVER_URL: kafka:9092
      KAFKA_LOG_TOPIC: logs
    restart: always
    depends_on:
      - producer
      - rabbit
      - kafka