version: '3'
services:
  rabbit:
    image: rabbitmq:alpine
    container_name: rabbit-broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for RabbitMQ GUI
    volumes:
      - ./aux/rabbitmq/data/:/var/lib/rabbitmq
      - ./aux/rabbitmq/log/:/var/log/rabbitmq
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    restart: always
    depends_on:
      - zookeeper

  btc-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
      KAFKA_BROKER_URL: localhost:9092
    ports:
      - 8080:8080
    depends_on:
      - rabbit
      - kafka